name: Node.js Docker CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - prod 
    paths-ignore:
      - '.github/workflows/manage-web-bak-ignorefile.yml'

jobs:
  build-and-deploy-nodejs-docker-ecr-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: hello-docker-node
        run: npm install

      - name: Lint / Test
        working-directory: hello-docker-node
        run: npm test || echo "No tests configured"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Set image tag with timestamp
        run: echo "IMAGE_TAG=node-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}
          docker build -t $IMAGE_REPO:$IMAGE_TAG hello-docker-node
          docker tag $IMAGE_REPO:$IMAGE_TAG $IMAGE_REPO:latest
          docker push $IMAGE_REPO:$IMAGE_TAG
          docker push $IMAGE_REPO:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Plan
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform plan \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="ecr_repo=${{ secrets.ECR_REPO }}" \
            -var="key_name=${{ secrets.EC2_KEY_NAME }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}"

      - name: Deploy with Terraform
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve \
            -var="image_tag=$IMAGE_TAG" \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="ecr_repo=${{ secrets.ECR_REPO }}" \
            -var="key_name=${{ secrets.EC2_KEY_NAME }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}"