name: Manage Onwuachi Web Server

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action (start, stop, upgrade)"
        required: true
        default: "start"
        type: choice
        options:
          - start
          - stop
          - upgrade

jobs:
  manage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/onwua_key.pem
          chmod 600 ~/.ssh/onwua_key.pem
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Test SSH connectivity
        run: |
          echo "Testing SSH connection to EC2 instance..."
          ssh -i ~/.ssh/onwua_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_PUBLIC_IP }} "echo '✅ SSH Connected Successfully!'"

      - name: Run selected action
        run: |
          EC2_IP="${{ secrets.EC2_PUBLIC_IP }}"
          echo "Running '${{ github.event.inputs.action }}' on Onwuachi web server ($EC2_IP)..."

          case "${{ github.event.inputs.action }}" in
            start) bash scripts/start-web.sh "$EC2_IP" ;;
            stop) bash scripts/stop-web.sh "$EC2_IP" ;;
            upgrade) bash scripts/upgrade-web.sh "$EC2_IP" ;;
            *) echo "Invalid action: ${{ github.event.inputs.action }}" ; exit 1 ;;
          esac