name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve deployment? (yes/no)'
        required: true
        default: 'no'
      environment:
        description: 'Target environment (dev, uat, stage, prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    if: |
      github.event.inputs.environment == 'dev' ||
      github.event.inputs.environment == 'uat' ||
      (github.event.inputs.environment == 'stage' && github.event.inputs.approve == 'yes') ||
      (github.event.inputs.environment == 'prod' && github.event.inputs.approve == 'yes')
    
    defaults:
        run:
          working-directory: infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Show MongoDB URL
        run: |
            echo "MongoDB Atlas URL: ${{ secrets.MONGODB_ATLAS_URL }}"