name: Terraform Simple Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev, uat, stage, prod)'
        required: true
        default: 'dev'
      approve:
        description: 'Approve deployment?'
        required: true
        default: 'no'

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    if: |
      github.event.inputs.environment == 'dev' ||
      github.event.inputs.environment == 'uat' ||
      (github.event.inputs.environment == 'stage' && github.event.inputs.approve == 'yes') ||
      (github.event.inputs.environment == 'prod' && github.event.inputs.approve == 'yes')

    defaults:
        run:
          working-directory: infra
        
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=environments/${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Show MongoDB URL
        run: |
          echo "MongoDB Atlas URL: ${{ secrets.MONGODB_ATLAS_URL }}"